### ISSUE TITLE
SPA - Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by romangazarek** [datapip/simple-data-layer-viewer-extension-v2#1]
Extension does not work with SPA (React or Angular) websites 🥲 . It works only on the very first page load and breaks when navigating to different pages.

**Steps to reproduce:**
1/ Go to SPA website (example: https://www.airbank.cz/)
2/ Navigate to other page
3/ Open Extension (Developers Tools or Extension icon)
4/ Check the errors in console

_Tested on latest version of Chrome for MacOS._

Could fix this issue? Thank you in advance :)

Kind regards
Roman Gazarek

![Screenshot 2023-01-25 at 16 16 36](https://user-images.githubusercontent.com/1630618/214601453-21519f95-9fe0-4b00-a4ed-f8b31379053d.png)
![Screenshot 2023-01-25 at 16 16 04](https://user-images.githubusercontent.com/1630618/214601457-d327f1e7-4a17-4c4f-92aa-a4252430ce79.png)
![Screenshot 2023-01-25 at 16 25 26](https://user-images.githubusercontent.com/1630618/214604248-55aeb264-4a0b-4837-9bb8-8c742366e035.png)

**Comment by datapip** [comment]
Hi @romangazarek, thank you for taking the time to report the issue.

The problem was that the dataLayer contained references to HTML elements - in this case anchor links. However, the JSON.stringify() method cannot handle such references.

With version 2.1.2 this should be fixed. I've already submitted this to Google and it usually takes several days for it to go live.

Thanks again!
